board: ["seeeduino_xiao_ble"]
shield: ["corne_xiao_left", "corne_xiao_right"]
include:
  - board: seeeduino_xiao_ble
    shield: corne_xiao_left
  - board: seeeduino_xiao_ble
    shield: corne_xiao_right